# Generated by Django 6.0.4 on 2026-04-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=255)),
                ('carga', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('regiao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_enderecos',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('endereco', models.ForeignKey(db_column='endereco_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle_aluno.endereco')),
            ],
            options={
                'db_table': 'tb_alunos',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aluno', models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='controle_aluno.aluno')),
                ('disciplina', models.ForeignKey(db_column='disciplina_id', on_delete=django.db.models.deletion.CASCADE, to='controle_aluno.disciplina')),
            ],
            options={
                'db_table': 'tb_notas',
            },
        ),
    ]
