# Generated by Django 6.0.4 on 2026-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
